version: '3.1'

services:
#  api:
#    image: openjdk:17-oraclelinux7
#    volumes:
#      - ../../../target/master-racing-online-0.0.1-SNAPSHOT.jar:/master-racing-online-0.0.1-SNAPSHOT.jar
#    ports:
#      - "8080:8080"
#    entrypoint: ["java","-jar","/master-racing-online-0.0.1-SNAPSHOT.jar"]
#    depends_on:
#      - db
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: master-racing-online