version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: master-racing-online